apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: url-shortener
          image: ????
          ports:
            - containerPort: 8080
              protocol: TCP
