name: Pull Request

on:
  pull_request:
    branches:
      - master

env:
  GO_VERSION: "^1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go Modules and builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: make lint

      - name: Test Unit
        run: make test-unit

      - name: Test Integration
        run: make test-integration
        env:
          SAFE_BROWSING_API_KEY: ${{ secret.SAFE_BROWSING_API_KEY }}
